//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklepik.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktury
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faktury()
        {
            this.Pozyjce_Faktury = new HashSet<Pozyjce_Faktury>();
        }
    
        public int IdFaktury { get; set; }
        public Nullable<int> IdKlienta { get; set; }
        public string nr_faktury { get; set; }
        public Nullable<System.DateTime> data_sprzedaży { get; set; }
        public string cena { get; set; }
        public string forma_płatności { get; set; }
        public string rodzaj_dokumentu { get; set; }
    
        public virtual Klientt Klientt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pozyjce_Faktury> Pozyjce_Faktury { get; set; }
    }
}
