//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklepik.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Galeria_zdjęc
    {
        public int Id_Galerii { get; set; }
        public Nullable<int> Id_Produktu { get; set; }
        public string nazwa { get; set; }
        public byte[] zdjęcie { get; set; }
    
        public virtual Produkty Produkty { get; set; }
    }
}
