//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklepik.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produkty()
        {
            this.Egzemplarze = new HashSet<Egzemplarze>();
            this.Galeria_zdjęc = new HashSet<Galeria_zdjęc>();
            this.zamówienia_produkty = new HashSet<zamówienia_produkty>();
        }
    
        public int Id_produktu { get; set; }
        public Nullable<int> id_katergoria_prod { get; set; }
        public string nazwa_produktu { get; set; }
        public string typ { get; set; }
        public string wersja { get; set; }
        public string opis { get; set; }
        public byte[] zdjęcie { get; set; }
        public string cena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Egzemplarze> Egzemplarze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Galeria_zdjęc> Galeria_zdjęc { get; set; }
        public virtual Kategorie_Producenci Kategorie_Producenci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zamówienia_produkty> zamówienia_produkty { get; set; }
    }
}
