//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklepik.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamówienia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zamówienia()
        {
            this.zamówienia_produkty = new HashSet<zamówienia_produkty>();
        }
    
        public int IdZam { get; set; }
        public Nullable<int> IdKli { get; set; }
        public Nullable<System.DateTime> data_złożenia_zamówienia { get; set; }
        public string czy_przyjeto_zam { get; set; }
        public Nullable<System.DateTime> data_przyjęcia_zam { get; set; }
        public string zapłacono { get; set; }
        public Nullable<System.DateTime> data_wysyłki { get; set; }
        public string czy_zam_zrealizowano { get; set; }
    
        public virtual Klientt Klientt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zamówienia_produkty> zamówienia_produkty { get; set; }
    }
}
